set_property BITSTREAM.CONFIG.USR_ACCESS TIMESTAMP [current_design]

# on-board LEDs
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[*]}]
set_property DRIVE 4 [get_ports {led_o[*]}]
set_property PACKAGE_PIN F16 [get_ports {led_o[0]}]
set_property PACKAGE_PIN F17 [get_ports {led_o[1]}]
set_property PACKAGE_PIN G15 [get_ports {led_o[2]}]
set_property PACKAGE_PIN H15 [get_ports {led_o[3]}]
set_property PACKAGE_PIN K14 [get_ports {led_o[4]}]
set_property PACKAGE_PIN G14 [get_ports {led_o[5]}]
set_property PACKAGE_PIN J15 [get_ports {led_o[6]}]
set_property PACKAGE_PIN J14 [get_ports {led_o[7]}]


# on-board clock (125 MHz)
set_property IOSTANDARD DIFF_HSTL_I_18  [get_ports adc_clk_i[*]]
set_property PACKAGE_PIN U18            [get_ports adc_clk_i[1]]
set_property PACKAGE_PIN U19            [get_ports adc_clk_i[0]]
# create_clock -period 8.000 -name adc_clk -waveform {0.000 4.000} [get_ports adc_clk_i[1]]
# set_input_jitter adc_clk 0.100


# PHpix Shield USB UART
# DIO_0_P
set_property PACKAGE_PIN G17            [get_ports {PHpix_uart_rx_i}]
# DIO_0_N
set_property PACKAGE_PIN G18            [get_ports {PHpix_uart_tx_o}]
set_property IOSTANDARD LVCMOS33        [get_ports {PHpix_uart_rx_i}]
set_property IOSTANDARD LVCMOS33        [get_ports {PHpix_uart_tx_o}]
set_property PULLUP true                [get_ports {PHpix_uart_rx_i}]


# PHpix SPI interface
# DIO_7_N
set_property PACKAGE_PIN M15 [get_ports PHpix_MOSI_o]
# DIO_6_N
set_property PACKAGE_PIN J16 [get_ports PHpix_SCK_o]
# DIO_5_N
set_property PACKAGE_PIN L17 [get_ports PHpix_MISO_i]
# DIO_4_N
set_property PACKAGE_PIN L15            [get_ports {PHpix_SCK_i}]


# DIO_7_P
set_property PACKAGE_PIN M14            [get_ports {PHpix_D_o}]
# DIO_6_P
set_property PACKAGE_PIN K16 [get_ports PHpix_CSn_o]
# DIO_5_P
# set_property PACKAGE_PIN L16            [get_ports {PHpix_D_i}]
# DIO_4_P
# set_property PACKAGE_PIN L14            [get_ports {PHpix_CSn_i}]



set_property IOSTANDARD LVCMOS33 [get_ports PHpix_CSn_o]
set_property IOSTANDARD LVCMOS33 [get_ports PHpix_SCK_o]
set_property IOSTANDARD LVCMOS33 [get_ports PHpix_MOSI_o]
set_property IOSTANDARD LVCMOS33        [get_ports {PHpix_D_o}]
set_property IOSTANDARD LVCMOS33 [get_ports PHpix_MISO_i]
# set_property IOSTANDARD LVCMOS33        [get_ports {PHpix_CSn_i}]
set_property IOSTANDARD LVCMOS33        [get_ports {PHpix_SCK_i}]
# set_property IOSTANDARD LVCMOS33        [get_ports {PHpix_D_i}]

set_property DRIVE 4 [get_ports PHpix_CSn_o]
set_property DRIVE 4 [get_ports PHpix_SCK_o]
set_property DRIVE 4 [get_ports PHpix_MOSI_o]
set_property DRIVE 4                    [get_ports {PHpix_D_o}]

set_property SLEW SLOW [get_ports PHpix_CSn_o]
set_property SLEW SLOW [get_ports PHpix_SCK_o]
set_property SLEW SLOW [get_ports PHpix_MOSI_o]
set_property SLEW SLOW                  [get_ports {PHpix_D_o}]


# set_property IOSTANDARD LVTTL [get_ports {DIO_*}]
# set_property SLEW FAST [get_ports {DIO_*}]
# set_property DRIVE 24 [get_ports {DIO_*}]       # LVTTL 4/8/12/16/24, LVCMOS33 4/8/12/16
#
# set_property PACKAGE_PIN G17 [get_ports {DIO_0_P}]         # PIN E1-3
# set_property PACKAGE_PIN G18 [get_ports {DIO_0_N}]         # PIN E1-4
# set_property PACKAGE_PIN H16 [get_ports {DIO_1_P}]         # PIN E1-5
# set_property PACKAGE_PIN H17 [get_ports {DIO_1_N}]         # PIN E1-6
# set_property PACKAGE_PIN J18 [get_ports {DIO_2_P}]         # PIN E1-7
# set_property PACKAGE_PIN H18 [get_ports {DIO_2_N}]         # PIN E1-8
# set_property PACKAGE_PIN K17 [get_ports {DIO_3_P}]         # PIN E1-9
# set_property PACKAGE_PIN K18 [get_ports {DIO_3_N}]         # PIN E1-10
# set_property PACKAGE_PIN L14 [get_ports {DIO_4_P}]         # PIN E1-11
# set_property PACKAGE_PIN L15 [get_ports {DIO_4_N}]         # PIN E1-12
# set_property PACKAGE_PIN L16 [get_ports {DIO_5_P}]         # PIN E1-13
# set_property PACKAGE_PIN L17 [get_ports {DIO_5_N}]         # PIN E1-14
# set_property PACKAGE_PIN K16 [get_ports {DIO_6_P}]         # PIN E1-15
# set_property PACKAGE_PIN J16 [get_ports {DIO_6_N}]         # PIN E1-16
# set_property PACKAGE_PIN M14 [get_ports {DIO_7_P}]         # PIN E1-17
# set_property PACKAGE_PIN M15 [get_ports {DIO_7_N}]         # PIN E1-18




set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[3]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[0]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[6]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[7]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[11]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[10]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_WE[2]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_WE[3]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[1]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[12]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[2]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[4]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[5]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[8]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[9]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_WE[0]}]
set_property MARK_DEBUG false [get_nets blok_i/axi_bram_ctrl_2_BRAM_PORTA_CLK]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_WE[1]}]

set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[3]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[0]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[1]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[2]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[25]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[23]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[24]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[21]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[22]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[19]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[20]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[4]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[8]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[14]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[15]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[16]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[17]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[18]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[6]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[5]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[31]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[29]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[30]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[27]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[28]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[7]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[9]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[10]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[11]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[12]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[13]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[26]}]
set_property MARK_DEBUG false [get_nets blok_i/axi_bram_ctrl_2_BRAM_PORTA_EN]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/inst/fsm_rx_bit_prt_reg_n_0_[0]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/inst/fsm_rx_bit_prt_reg_n_0_[2]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/inst/fsm_rx_bit_prt_reg_n_0_[3]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/inst/fsm_rx_bit_prt_reg_n_0_[4]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/inst/fsm_rx_bit_prt_reg_n_0_[1]}]
set_property MARK_DEBUG true [get_nets {blok_i/controller_0/datmem_addr_o[0]}]
set_property MARK_DEBUG true [get_nets {blok_i/controller_0/cfgmem_addr_o[0]}]

set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[5]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[1]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[13]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[14]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[15]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[16]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[2]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[3]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[4]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[6]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[7]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[8]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[9]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[10]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[11]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[12]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[20]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[17]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[31]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[29]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[30]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[27]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[28]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[18]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[19]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[21]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[22]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[23]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[24]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[25]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[26]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[3]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[0]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[1]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[2]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[4]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[5]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[6]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[7]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[25]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[26]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[27]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[28]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[29]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[30]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[31]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[17]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[18]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[19]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[20]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[21]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[22]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[23]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[24]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[8]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[9]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[10]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[11]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[12]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[13]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[14]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[15]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[16]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[14]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[10]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[27]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[28]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[29]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[30]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[23]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[24]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[25]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[26]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[19]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[20]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[21]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[22]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[11]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[12]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[13]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[15]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[16]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[17]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[18]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[31]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[0]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[1]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[2]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[3]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[4]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[5]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[6]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[7]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[8]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[9]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[4]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[0]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[1]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[2]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[27]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[28]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[29]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[30]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[23]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[24]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[25]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[26]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[19]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[20]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[21]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[22]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[15]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[16]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[17]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[18]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[31]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[3]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[5]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[6]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[7]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[8]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[9]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[11]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[12]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[13]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[14]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[10]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[5]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[1]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[2]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[3]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[24]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[25]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[26]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[27]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[20]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[21]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[22]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[23]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[16]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[17]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[18]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[19]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[12]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[13]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[14]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[15]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[28]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[29]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[30]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[31]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[4]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[6]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[7]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[8]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[9]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[10]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[11]}]
set_property MARK_DEBUG false [get_nets blok_i/controller_0/mosi_o]
set_property MARK_DEBUG false [get_nets blok_i/controller_0/cs_o]



set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[3]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[0]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[1]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[2]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[4]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[5]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[6]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[7]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[13]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[14]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[11]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[12]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[8]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[9]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[10]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[0]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[5]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[1]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[2]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[3]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[4]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[6]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[7]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[8]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[9]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[10]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[15]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[16]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[13]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[14]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[19]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[20]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[17]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[18]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[23]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[24]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[21]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[22]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[27]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[25]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[26]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[11]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[12]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[28]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[29]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[30]}]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[31]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[6]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[2]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[0]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[1]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[3]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[4]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[5]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[7]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[8]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[9]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[12]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[13]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[10]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[11]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[16]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[17]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[14]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[15]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[21]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[22]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[18]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[19]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[25]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[26]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[23]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[24]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[31]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[29]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[30]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[20]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[27]}]
set_property MARK_DEBUG false [get_nets {blok_i/blk_mem_gen_1_doutb[28]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[5]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[1]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[0]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[2]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[3]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[4]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[6]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[12]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[13]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[7]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[8]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[10]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[11]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[18]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[19]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[16]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[17]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[22]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[23]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[20]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[21]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[27]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[28]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[24]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[25]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[31]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[29]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[30]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[9]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[14]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[15]}]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0_cfgmem_addr_o[26]}]
set_property MARK_DEBUG false [get_nets blok_i/axi_bram_ctrl_0_BRAM_PORTA_EN]
set_property MARK_DEBUG false [get_nets blok_i/axi_bram_ctrl_0_BRAM_PORTA_RST]
set_property MARK_DEBUG false [get_nets blok_i/controller_0_cfgmem_ena_o]
set_property MARK_DEBUG false [get_nets blok_i/controller_0_cfgmem_rst_o]
