# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pinout.xdc

# Block Designs: bd/blok/blok.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blok || ORIG_REF_NAME==blok} -quiet] -quiet

# IP: bd/blok/ip/blok_processing_system7_0_0/blok_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blok_processing_system7_0_0 || ORIG_REF_NAME==blok_processing_system7_0_0} -quiet] -quiet

# IP: bd/blok/ip/blok_xbar_0/blok_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blok_xbar_0 || ORIG_REF_NAME==blok_xbar_0} -quiet] -quiet

# IP: bd/blok/ip/blok_axi_interconnect_0_0/blok_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blok_axi_interconnect_0_0 || ORIG_REF_NAME==blok_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/blok/ip/blok_rst_ps7_0_50M_0/blok_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blok_rst_ps7_0_50M_0 || ORIG_REF_NAME==blok_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/blok/ip/blok_axi_bram_ctrl_0_0/blok_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blok_axi_bram_ctrl_0_0 || ORIG_REF_NAME==blok_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/blok/ip/blok_axi_bram_ctrl_0_1/blok_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blok_axi_bram_ctrl_0_1 || ORIG_REF_NAME==blok_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/blok/ip/blok_axi_bram_ctrl_1_0/blok_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blok_axi_bram_ctrl_1_0 || ORIG_REF_NAME==blok_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/blok/ip/blok_blk_mem_gen_0_0/blok_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blok_blk_mem_gen_0_0 || ORIG_REF_NAME==blok_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/blok/ip/blok_blk_mem_gen_0_1/blok_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blok_blk_mem_gen_0_1 || ORIG_REF_NAME==blok_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/blok/ip/blok_controller_0_0/blok_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blok_controller_0_0 || ORIG_REF_NAME==blok_controller_0_0} -quiet] -quiet

# IP: bd/blok/ip/blok_decoder_0_0/blok_decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blok_decoder_0_0 || ORIG_REF_NAME==blok_decoder_0_0} -quiet] -quiet

# IP: bd/blok/ip/blok_auto_pc_0/blok_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blok_auto_pc_0 || ORIG_REF_NAME==blok_auto_pc_0} -quiet] -quiet

# XDC: /home/zz/phpix/phpix-vivado-peta/hw_linux/clean_hw/clean_hw.gen/sources_1/bd/blok/blok_ooc.xdc
