set_property SRC_FILE_INFO {cfile:/home/zz/phpix/phpix-vivado-peta/hw_linux/clean_hw/clean_hw.srcs/constrs_1/new/pinout.xdc rfile:../../../clean_hw.srcs/constrs_1/new/pinout.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F16 [get_ports {led_o[0]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports {led_o[1]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports {led_o[2]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports {led_o[3]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K14 [get_ports {led_o[4]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {led_o[5]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {led_o[6]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J14 [get_ports {led_o[7]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_HSTL_I_18  [get_ports adc_clk_i[*]]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18            [get_ports adc_clk_i[1]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19            [get_ports adc_clk_i[0]]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17            [get_ports {PHpix_uart_rx_i}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18            [get_ports {PHpix_uart_tx_o}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33        [get_ports {PHpix_uart_rx_i}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33        [get_ports {PHpix_uart_tx_o}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true                [get_ports {PHpix_uart_rx_i}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports PHpix_MOSI_o]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16 [get_ports PHpix_SCK_o]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17 [get_ports PHpix_MISO_i]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15            [get_ports {PHpix_SCK_i}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14            [get_ports {PHpix_D_o}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports PHpix_CSn_o]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33        [get_ports {PHpix_D_o}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33        [get_ports {PHpix_SCK_i}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 4                    [get_ports {PHpix_D_o}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW                  [get_ports {PHpix_D_o}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[3]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[0]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[6]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[7]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[11]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[10]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_WE[2]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_WE[3]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[1]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[12]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[2]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[4]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[5]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[8]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_ADDR[9]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_WE[0]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets blok_i/axi_bram_ctrl_2_BRAM_PORTA_CLK]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_WE[1]}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[3]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[0]}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[1]}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[2]}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[25]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[23]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[24]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[21]}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[22]}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[19]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[20]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[4]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[8]}]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[14]}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[15]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[16]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[17]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[18]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[6]}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[5]}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[31]}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[29]}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[30]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[27]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[28]}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[7]}]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[9]}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[10]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[11]}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[12]}]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[13]}]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/axi_bram_ctrl_2_BRAM_PORTA_DIN[26]}]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets blok_i/axi_bram_ctrl_2_BRAM_PORTA_EN]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/inst/fsm_rx_bit_prt_reg_n_0_[0]}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/inst/fsm_rx_bit_prt_reg_n_0_[2]}]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/inst/fsm_rx_bit_prt_reg_n_0_[3]}]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/inst/fsm_rx_bit_prt_reg_n_0_[4]}]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/inst/fsm_rx_bit_prt_reg_n_0_[1]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {blok_i/controller_0/datmem_addr_o[0]}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {blok_i/controller_0/cfgmem_addr_o[0]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[5]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[1]}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[13]}]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[14]}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[15]}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[16]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[2]}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[3]}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[4]}]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[6]}]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[7]}]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[8]}]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[9]}]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[10]}]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[11]}]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[12]}]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[20]}]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[17]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[31]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[29]}]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[30]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[27]}]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[28]}]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[18]}]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[19]}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[21]}]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[22]}]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[23]}]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[24]}]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[25]}]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_addr_o[26]}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[3]}]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[0]}]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[1]}]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[2]}]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[4]}]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[5]}]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[6]}]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[7]}]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[25]}]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[26]}]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[27]}]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[28]}]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[29]}]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[30]}]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[31]}]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[17]}]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[18]}]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[19]}]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[20]}]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[21]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[22]}]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[23]}]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[24]}]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[8]}]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[9]}]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[10]}]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[11]}]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[12]}]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[13]}]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[14]}]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[15]}]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/cfgmem_data_i[16]}]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[14]}]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[10]}]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[27]}]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[28]}]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[29]}]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[30]}]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[23]}]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[24]}]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[25]}]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[26]}]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[19]}]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[20]}]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[21]}]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[22]}]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[11]}]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[12]}]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[13]}]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[15]}]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[16]}]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[17]}]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[18]}]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[31]}]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[0]}]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[1]}]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[2]}]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[3]}]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[4]}]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[5]}]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[6]}]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[7]}]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[8]}]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_addr_i[9]}]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[4]}]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[0]}]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[1]}]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[2]}]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[27]}]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[28]}]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[29]}]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[30]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[23]}]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[24]}]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[25]}]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[26]}]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[19]}]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[20]}]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[21]}]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[22]}]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[15]}]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[16]}]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[17]}]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[18]}]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[31]}]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[3]}]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[5]}]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[6]}]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[7]}]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[8]}]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[9]}]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[11]}]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[12]}]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[13]}]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[14]}]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/ctl_data_i[10]}]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[5]}]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[1]}]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[2]}]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[3]}]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[24]}]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[25]}]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[26]}]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[27]}]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[20]}]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[21]}]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[22]}]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[23]}]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[16]}]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[17]}]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[18]}]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[19]}]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[12]}]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[13]}]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[14]}]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[15]}]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[28]}]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[29]}]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[30]}]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[31]}]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[4]}]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[6]}]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[7]}]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[8]}]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[9]}]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[10]}]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {blok_i/controller_0/datmem_addr_o[11]}]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets blok_i/controller_0/mosi_o]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets blok_i/controller_0/cs_o]
