# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zz/phpix/phpix-vivado-peta/hw_linux/clean_hw/clean_hw.srcs/sources_1/bd/blok/ip/blok_blk_mem_gen_0_0/blok_blk_mem_gen_0_0.xci
# IP: The module: 'blok_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zz/phpix/phpix-vivado-peta/hw_linux/clean_hw/clean_hw.gen/sources_1/bd/blok/ip/blok_blk_mem_gen_0_0/blok_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blok_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/zz/phpix/phpix-vivado-peta/hw_linux/clean_hw/clean_hw.srcs/sources_1/bd/blok/ip/blok_blk_mem_gen_0_0/blok_blk_mem_gen_0_0.xci
# IP: The module: 'blok_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zz/phpix/phpix-vivado-peta/hw_linux/clean_hw/clean_hw.gen/sources_1/bd/blok/ip/blok_blk_mem_gen_0_0/blok_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blok_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
